=== cmmcleod/coriolis/src/schemas/ship-loadout/2.json
{
  "$schema":            "http://json-schema.org/draft-04/schema#",
  "id":                 "https://coriolis.edcd.io/schemas/ship-loadout/2.json#",
  "title":              "Ship Loadout",
  "type":               "object",
  "description":        "The details for a specific ship build/loadout. DEPRECATED in favor of Version 3",
  "required":           ["name", "ship", "components"],
  "properties": {
    "name": {
      "description":    "The name of the build/loadout",
      "type":           "string",
      "minLength":      2
    },
    "ship": {
      "description":    "The full display name of the ship",
      "type":           "string",
      "minimum":        3
    },
    "manufacturer": {
      "description":    "The ship manufacturer",
      "type":           "string"
    },
    "references" : {
      "description":    "3rd Party references and/or links to this build/loadout",
      "type":           "array",
      "items": {
        "type":                 "object",
        "required":             ["name","url"],
        "additionalProperties": true,
        "properties": {
          "name": {
            "description":  "The name of the 3rd party, .e.g 'Coriolis.io' or 'E:D Shipyard'",
            "type":         "string"
          },
          "url": {
            "description":  "The link/url to the 3rd party referencing this build/loadout",
            "type":         "string"
          }
        }
      }
    },
    "components": {
      "description":                "The components used by this build",
      "type":                       "object",
      "additionalProperties":       false,
      "required":                   ["standard", "internal", "hardpoints", "utility"],
      "properties": {
        "standard": {
          "description":            "The set of standard components across all ships",
          "type":                   "object",
          "additionalProperties":   false,
          "required":               ["bulkheads", "powerPlant", "thrusters", "frameShiftDrive", "lifeSupport", "powerDistributor", "sensors", "fuelTank", "cargoHatch"],
          "properties": {
            "bulkheads": {
              "enum":               ["Lightweight Alloy", "Reinforced Alloy", "Military Grade Composite", "Mirrored Surface Composite", "Reactive Surface Composite"]
            },
            "cargoHatch": {
              "required": ["enabled", "priority"],
              "properties": {
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "powerPlant": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "thrusters": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "frameShiftDrive": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "lifeSupport": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 6 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "powerDistributor": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "sensors": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "fuelTank": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 6 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            }
          }
        },
        "internal": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group"],
            "properties" : {
              "class": { "type": "integer", "minimum": 1, "maximum": 8 },
              "rating": { "$ref": "#/definitions/standardRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "group": {
                "description": "The group of the component, e.g. 'Shield Generator', or 'Cargo Rack'",
                "type": "string"
              },
              "name": {
                "description": "The name identifying the component (if applicable), e.g. 'Advance Discovery Scanner', or 'Detailed Surface Scanner'",
                "type": "string"
              }
            }
          },
          "minItems": 3
        },
        "hardpoints": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group", "mount"],
            "properties" : {
              "class": { "type": "integer", "minimum": 1, "maximum": 4 },
              "rating": { "$ref": "#/definitions/allRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "mount": { "type": "string", "enum": ["Fixed", "Gimballed", "Turret"] },
              "group": {
                "description": "The group of the component, e.g. 'Beam Laser', or 'Missile Rack'",
                "type": "string"
              },
              "name": {
                "description": "The name identifing the component (if applicable), e.g. 'Retributor', or 'Mining Lance'",
                "type": "string"
              }
            }
          },
          "minItems": 1
        },
        "utility": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group"],
            "properties" : {
              "class": { "type": "integer", "minimum": 0, "maximum": 0 },
              "rating": { "$ref": "#/definitions/allRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "group": {
                "description": "The group of the component, e.g. 'Shield Booster', or 'Kill Warrant Scanner'",
                "type": "string"
              },
              "name": {
                "description": "The name identifing the component (if applicable), e.g. 'Point Defence', or 'Electronic Countermeasure'",
                "type": "string"
              }
            }
          },
          "minItems": 1
        }
      }
    },
    "stats": {
      "description":          "Optional statistics from the build",
      "type":                 "object",
      "additionalProperties": true,
      "properties": {
        "agility": {
          "type":         "integer",
          "minimum":      0
        },
        "armour": {
          "description":  "Sum of base armour + any hull reinforcements",
          "type":         "integer",
          "minimum":      1
        },
        "armourAdded":{
          "description":  "Armour added through Hull reinforcement",
          "type":         "integer",
          "minimum":      1
        },
        "baseShieldStrength": {
          "type":         "integer",
          "minimum":      1
        },
        "baseArmour":  {
          "type":         "integer",
          "minimum":      1
        },
        "boost": {
          "description":  "Maximum boost speed of the ships (4 pips, straight-line)",
          "type":         "number",
          "minimum":      1
        },
        "cargoCapacity": {
          "type":         "integer",
          "minimum":      0
        },
        "class": {
          "description":  "Ship Class/Size [Small, Medium, Large]",
          "enum":         [1,2,3]
        },
        "dps": {
          "description":  "Cumulative DPS based on the in-game 1-10 statistic",
          "type":         "integer",
          "minimum":      0
        },
        "hullCost": {
          "description":  "Cost of the ship's hull",
          "type":         "integer",
          "minimum":      1
        },
        "hullMass": {
          "description":  "Mass of the Ship hull only",
          "type":         "number",
          "minimum":      1
        },
        "fuelCapacity": {
          "type":         "integer",
          "minimum":      1
        },
        "fullTankRange": {
          "description":  "Single Jump range with a full tank (unladenMass + fuel)",
          "type":         "number",
          "minimum":      0
        },
        "ladenMass": {
          "description":  "Mass of the Ship + fuel + cargo (hull + all components + fuel tank + cargo capacity)",
          "type":         "number",
          "minimum":      1
        },
        "ladenRange": {
          "description":  "Single Jump range with full cargo load, see ladenMass",
          "type":         "number",
          "minimum":      0
        },
        "masslock": {
          "description":  "Mass Lock Factor of the Ship",
          "type":         "integer",
          "minimum":      1
        },
        "shieldStrength": {
          "description":  "Shield strengh in Mega Joules (Mj)",
          "type":         "number",
          "minimum":      0
        },
        "speed": {
          "description":  "Maximum speed of the ships (4 pips, straight-line)",
          "type":         "number",
          "minimum":      1
        },
        "totalCost":  {
          "type":         "integer",
          "minimum":      1
        },
        "unladenRange": {
          "description":  "Single Jump range when unladen, see unladenMass",
          "type":         "number",
          "minimum":      0
        },
        "unladenMass": {
          "description":  "Mass of the Ship (hull + all components)",
          "type":         "number",
          "minimum":      1
        }
      }
    }
  },
  "definitions": {
    "standardRatings":  { "enum": ["A", "B", "C", "D", "E", "F", "G", "H"] },
    "allRatings":       { "enum": ["A", "B", "C", "D", "E", "F", "G", "H", "I" ] }
  }
}

=== cmmcleod/coriolis/__tests__/fixtures/courier-test-detailed-export-v4.json
{
  "$schema": "http://cdn.coriolis.io/schemas/ship-loadout/4.json#",
  "name": "Multi-purpose Imperial Courier",
  "ship": "Imperial Courier",
  "references": [
    {
      "name": "Coriolis.io",
      "url": "https://coriolis.edcd.io/outfit/imperial_courier?code=0patzF5l0das8f31a1a270202000e402t0101-2f.AwRj4zKA.CwRgDBldLiQ%3D.H4sIAAAAAAAAA12OP0tCYRjFj9fuVbvF1du9ekkT8s%2FkIg4NElyIBBd321yaGvwUQTS3N7UFfYygIT9EoyQUJA36ns47XJCWA%2B%2Fz%2Bz3Pe3ImBbDNKaqNPSBoGrL4ngfomKpFGiJ%2BLgHteR1IPjxJT5pF11uSeXNsJVcRfgdC92syWUuK0iMdKZqrjJ%2F0aoA71lJ5oKf38knWcCiptCPdhJIerdS00vlK0qktlqoj983UmqqHjQ33VsW8eazFmaTyULP2hQ4lX8LBme6g%2F6v0TTdbxJ2KhdEIaCw15MF%2FNB0L%2BS2hwEwyFM8KgP%2BqEpWWA3Qu9Z3z9kPWHzakt7Dt%2BAeD7ghSTgEAAA%3D%3D&bn=Multi-purpose%20Imperial%20Courier",
      "code": "0patzF5l0das8f31a1a270202000e402t0101-2f.AwRj4zKA.CwRgDBldLiQ=.H4sIAAAAAAAAA12OP0tCYRjFj9fuVbvF1du9ekkT8s/kIg4NElyIBBd321yaGvwUQTS3N7UFfYygIT9EoyQUJA36ns47XJCWA+/z+z3Pe3ImBbDNKaqNPSBoGrL4ngfomKpFGiJ+LgHteR1IPjxJT5pF11uSeXNsJVcRfgdC92syWUuK0iMdKZqrjJ/0aoA71lJ5oKf38knWcCiptCPdhJIerdS00vlK0qktlqoj983UmqqHjQ33VsW8eazFmaTyULP2hQ4lX8LBme6g/6v0TTdbxJ2KhdEIaCw15MF/NB0L+S2hwEwyFM8KgP+qEpWWA3Qu9Z3z9kPWHzakt7Dt+AeD7ghSTgEAAA==",
      "shipId": "imperial_courier"
    }
  ],
  "components": {
    "standard": {
      "bulkheads": "Lightweight Alloy",
      "cargoHatch": {
        "enabled": false,
        "priority": 5
      },
      "powerPlant": {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 2,
        "modifications": {
          "pgen": 1052,
          "integrity": -482,
          "eff": 974
        },
        "blueprint": {
          "id": 63,
          "name": "Overcharged",
          "grade": 1
        }
      },
      "thrusters": {
        "class": 3,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "name": "Enhanced Performance",
        "modifications": {
          "optmul": 2476,
          "thermload": 7023,
          "power": 1763,
          "integrity": 165,
          "optmass": -667
        },
        "blueprint": {
          "id": 22,
          "name": "Dirty",
          "grade": 4
        }
      },
      "frameShiftDrive": {
        "class": 3,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "mass": 4082,
          "integrity": -2422,
          "power": 1782,
          "optmass": 4927
        },
        "blueprint": {
          "id": 26,
          "name": "Increased range",
          "grade": 5
        }
      },
      "lifeSupport": {
        "class": 1,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "powerDistributor": {
        "class": 3,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "sensors": {
        "class": 2,
        "rating": "D",
        "enabled": true,
        "priority": 1
      },
      "fuelTank": {
        "class": 3,
        "rating": "C",
        "enabled": true,
        "priority": 1
      }
    },
    "hardpoints": [
      {
        "class": 2,
        "rating": "F",
        "enabled": true,
        "priority": 1,
        "group": "Pulse Laser",
        "mount": "Fixed",
        "modifications": {
          "rof": 5931,
          "damage": -184,
          "jitter": 50,
          "distdraw": -4689,
          "piercing": 3328
        },
        "blueprint": {
          "id": 89,
          "name": "Rapid fire",
          "grade": 5
        }
      },
      {
        "class": 2,
        "rating": "F",
        "enabled": true,
        "priority": 1,
        "group": "Pulse Laser",
        "mount": "Fixed",
        "modifications": {
          "rof": 4715,
          "damage": -97,
          "jitter": 30,
          "distdraw": -4548,
          "piercing": 1057,
          "integrity": 319
        },
        "blueprint": {
          "id": 89,
          "name": "Rapid fire",
          "grade": 5
        }
      },
      {
        "class": 2,
        "rating": "F",
        "enabled": true,
        "priority": 1,
        "group": "Multi-cannon",
        "mount": "Gimballed",
        "modifications": {
          "damage": 2437,
          "distdraw": 5487,
          "rof": 1120,
          "jitter": 58,
          "thermload": 1346,
          "power": 1009,
          "integrity": -202,
          "ammo": -2000
        },
        "blueprint": {
          "id": 88,
          "name": "Overcharged",
          "grade": 3,
          "special": {
            "id": 3,
            "name": "Corrosive shell"
          }
        }
      }
    ],
    "utility": [
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Heat Sink Launcher",
        "name": "Heat Sink Launcher",
        "modifications": {
          "ammo": 5000,
          "mass": 17684,
          "reload": 9707
        },
        "blueprint": {
          "id": 37,
          "name": "Ammo capacity",
          "grade": 3
        }
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Heat Sink Launcher",
        "name": "Heat Sink Launcher",
        "modifications": {
          "ammo": 5000,
          "mass": 18520,
          "reload": 8715
        },
        "blueprint": {
          "id": 37,
          "name": "Ammo capacity",
          "grade": 3
        }
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Chaff Launcher",
        "name": "Chaff Launcher"
      },
      {
        "class": 0,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Frame Shift Wake Scanner"
      }
    ],
    "internal": [
      {
        "class": 3,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Generator",
        "modifications": {
          "optmul": 1888,
          "explres": 455,
          "kinres": 546,
          "thermres": 1092,
          "brokenregen": -2614,
          "regen": -876,
          "distdraw": 463
        },
        "blueprint": {
          "id": 77,
          "name": "Reinforced",
          "grade": 3
        }
      },
      {
        "class": 3,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Fuel Scoop"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cargo Rack"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cargo Rack"
      },
      null,
      {
        "class": 1,
        "rating": "C",
        "enabled": true,
        "priority": 2,
        "group": "Scanner",
        "name": "Advanced Discovery Scanner"
      }
    ]
  },
  "stats": {
    "class": 1,
    "hullCost": 2481550,
    "speed": 280,
    "boost": 380,
    "boostEnergy": 10,
    "agility": 6,
    "baseShieldStrength": 200,
    "baseArmour": 80,
    "hullMass": 35,
    "masslock": 7,
    "pipSpeed": 0.05,
    "moduleCostMultiplier": 1,
    "fuelCapacity": 8,
    "cargoCapacity": 8,
    "ladenMass": 104.25,
    "armour": 144,
    "shield": 404.19,
    "shieldCells": 0,
    "totalCost": 14059860,
    "unladenMass": 88.25,
    "totalDpe": 32.25,
    "totalExplDpe": 0,
    "totalKinDpe": 9.41,
    "totalThermDpe": 22.84,
    "totalDps": 53.8,
    "totalExplDps": 0,
    "totalKinDps": 17.44,
    "totalThermDps": 36.35,
    "totalSDps": 48.99,
    "totalExplSDps": 0,
    "totalKinSDps": 12.64,
    "totalThermSDps": 36.35,
    "totalEps": 9.84,
    "totalHps": 12.28,
    "shieldExplRes": 0.48,
    "shieldKinRes": 0.55,
    "shieldThermRes": 1.09,
    "hullExplRes": 1.4,
    "hullKinRes": 1.2,
    "hullThermRes": 1,
    "powerAvailable": 17.24,
    "powerRetracted": 11.3,
    "powerDeployed": 16.41,
    "unladenRange": 25.57,
    "fullTankRange": 23.92,
    "ladenRange": 22.09,
    "unladenFastestRange": 116.23,
    "ladenFastestRange": 107,
    "maxJumpCount": 5,
    "topSpeed": 386.56,
    "topBoost": 524.62
  }
}

=== cmmcleod/coriolis/test/fixtures/anaconda-test-detailed-export-v2.json
{
  "$schema": "http://cdn.coriolis.io/schemas/ship-loadout/2.json#",
  "name": "Test",
  "ship": "Anaconda",
  "references": [
    {
      "name": "Coriolis.io",
      "url": "http://localhost:3300/outfit/anaconda/48A6A6A5A8A8A5C2c0o0o0o1m1m0q0q0404-0l0b0100034k5n052d04--0303326b.Iw18QDBNA%3D%3D%3D.AwhMJBGaei%2BJCyyiA%3D%3D%3D?bn=Test",
      "code": "48A6A6A5A8A8A5C2c0o0o0o1m1m0q0q0404-0l0b0100034k5n052d04--0303326b.Iw18QDBNA===.AwhMJBGaei+JCyyiA===",
      "shipId": "anaconda"
    }
  ],
  "components": {
    "standard": {
      "bulkheads": "Reactive Surface Composite",
      "cargoHatch": {
        "enabled": false,
        "priority": 5
      },
      "powerPlant": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "thrusters": {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "frameShiftDrive": {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 3
      },
      "lifeSupport": {
        "class": 5,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "powerDistributor": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "sensors": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "fuelTank": {
        "class": 5,
        "rating": "C",
        "enabled": true,
        "priority": 1
      }
    },
    "hardpoints": [
      {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 2,
        "group": "Plasma Accelerator",
        "mount": "Fixed"
      },
      {
        "class": 3,
        "rating": "D",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 3,
        "rating": "D",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 3,
        "rating": "D",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cannon",
        "mount": "Turret"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cannon",
        "mount": "Turret"
      },
      {
        "class": 1,
        "rating": "F",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 1,
        "rating": "F",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      }
    ],
    "utility": [
      {
        "class": 0,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Booster"
      },
      {
        "class": 0,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Booster"
      },
      null,
      {
        "class": 0,
        "rating": "C",
        "enabled": true,
        "priority": 2,
        "group": "Kill Warrant Scanner"
      },
      {
        "class": 0,
        "rating": "C",
        "enabled": true,
        "priority": 2,
        "group": "Cargo Scanner"
      },
      {
        "class": 0,
        "rating": "F",
        "enabled": false,
        "priority": 1,
        "group": "Countermeasure",
        "name": "Electronic Countermeasure"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Countermeasure",
        "name": "Chaff Launcher"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 2,
        "group": "Countermeasure",
        "name": "Point Defence"
      }
    ],
    "internal": [
      {
        "class": 7,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Generator"
      },
      {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Cell Bank"
      },
      {
        "class": 6,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      {
        "class": 5,
        "rating": "D",
        "enabled": true,
        "priority": 1,
        "group": "Hull Reinforcement Package"
      },
      {
        "class": 5,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      null,
      null,
      {
        "class": 4,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      {
        "class": 4,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 3,
        "group": "Fuel Scoop"
      },
      {
        "class": 2,
        "rating": "A",
        "enabled": true,
        "priority": 3,
        "group": "Frame Shift Drive Interdictor"
      }
    ]
  },
  "stats": {
    "class": 3,
    "hullCost": 141889930,
    "speed": 180,
    "topSpeed": 186.5,
    "boost": 240,
    "boostEnergy": 29,
    "topBoost": 248.66,
    "agility": 2,
    "baseShieldStrength": 350,
    "baseArmour": 945,
    "hullMass": 400,
    "masslock": 23,
    "pipSpeed": 0.14,
    "shipCostMultiplier": 1,
    "componentCostMultiplier": 1,
    "fuelCapacity": 32,
    "cargoCapacity": 128,
    "ladenMass": 1339.2,
    "armour": 2228,
    "armourAdded": 390,
    "armourMultiplier": 1.95,
    "shieldMultiplier": 1.4,
    "totalCost": 882362060,
    "unladenMass": 1179.2,
    "totalDps": 29,
    "powerAvailable": 36,
    "powerRetracted": 23.33,
    "powerDeployed": 34.76,
    "unladenRange": 18.49,
    "fullTankRange": 18.12,
    "ladenRange": 16.39,
    "unladenTotalRange": 73.21,
    "ladenTotalRange": 66.15,
    "maxJumpCount": 4,
    "shieldStrength": 833
  }
}
