=== cmmcleod/coriolis/src/schemas/ship-loadout/2.json
{
  "$schema":            "http://json-schema.org/draft-04/schema#",
  "id":                 "https://coriolis.edcd.io/schemas/ship-loadout/2.json#",
  "title":              "Ship Loadout",
  "type":               "object",
  "description":        "The details for a specific ship build/loadout. DEPRECATED in favor of Version 3",
  "required":           ["name", "ship", "components"],
  "properties": {
    "name": {
      "description":    "The name of the build/loadout",
      "type":           "string",
      "minLength":      2
    },
    "ship": {
      "description":    "The full display name of the ship",
      "type":           "string",
      "minimum":        3
    },
    "manufacturer": {
      "description":    "The ship manufacturer",
      "type":           "string"
    },
    "references" : {
      "description":    "3rd Party references and/or links to this build/loadout",
      "type":           "array",
      "items": {
        "type":                 "object",
        "required":             ["name","url"],
        "additionalProperties": true,
        "properties": {
          "name": {
            "description":  "The name of the 3rd party, .e.g 'Coriolis.io' or 'E:D Shipyard'",
            "type":         "string"
          },
          "url": {
            "description":  "The link/url to the 3rd party referencing this build/loadout",
            "type":         "string"
          }
        }
      }
    },
    "components": {
      "description":                "The components used by this build",
      "type":                       "object",
      "additionalProperties":       false,
      "required":                   ["standard", "internal", "hardpoints", "utility"],
      "properties": {
        "standard": {
          "description":            "The set of standard components across all ships",
          "type":                   "object",
          "additionalProperties":   false,
          "required":               ["bulkheads", "powerPlant", "thrusters", "frameShiftDrive", "lifeSupport", "powerDistributor", "sensors", "fuelTank", "cargoHatch"],
          "properties": {
            "bulkheads": {
              "enum":               ["Lightweight Alloy", "Reinforced Alloy", "Military Grade Composite", "Mirrored Surface Composite", "Reactive Surface Composite"]
            },
            "cargoHatch": {
              "required": ["enabled", "priority"],
              "properties": {
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "powerPlant": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "thrusters": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "frameShiftDrive": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "lifeSupport": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 6 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "powerDistributor": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "sensors": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "fuelTank": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 6 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            }
          }
        },
        "internal": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group"],
            "properties" : {
              "class": { "type": "integer", "minimum": 1, "maximum": 8 },
              "rating": { "$ref": "#/definitions/standardRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "group": {
                "description": "The group of the component, e.g. 'Shield Generator', or 'Cargo Rack'",
                "type": "string"
              },
              "name": {
                "description": "The name identifying the component (if applicable), e.g. 'Advance Discovery Scanner', or 'Detailed Surface Scanner'",
                "type": "string"
              }
            }
          },
          "minItems": 3
        },
        "hardpoints": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group", "mount"],
            "properties" : {
              "class": { "type": "integer", "minimum": 1, "maximum": 4 },
              "rating": { "$ref": "#/definitions/allRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "mount": { "type": "string", "enum": ["Fixed", "Gimballed", "Turret"] },
              "group": {
                "description": "The group of the component, e.g. 'Beam Laser', or 'Missile Rack'",
                "type": "string"
              },
              "name": {
                "description": "The name identifing the component (if applicable), e.g. 'Retributor', or 'Mining Lance'",
                "type": "string"
              }
            }
          },
          "minItems": 1
        },
        "utility": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group"],
            "properties" : {
              "class": { "type": "integer", "minimum": 0, "maximum": 0 },
              "rating": { "$ref": "#/definitions/allRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "group": {
                "description": "The group of the component, e.g. 'Shield Booster', or 'Kill Warrant Scanner'",
                "type": "string"
              },
              "name": {
                "description": "The name identifing the component (if applicable), e.g. 'Point Defence', or 'Electronic Countermeasure'",
                "type": "string"
              }
            }
          },
          "minItems": 1
        }
      }
    },
    "stats": {
      "description":          "Optional statistics from the build",
      "type":                 "object",
      "additionalProperties": true,
      "properties": {
        "agility": {
          "type":         "integer",
          "minimum":      0
        },
        "armour": {
          "description":  "Sum of base armour + any hull reinforcements",
          "type":         "integer",
          "minimum":      1
        },
        "armourAdded":{
          "description":  "Armour added through Hull reinforcement",
          "type":         "integer",
          "minimum":      1
        },
        "baseShieldStrength": {
          "type":         "integer",
          "minimum":      1
        },
        "baseArmour":  {
          "type":         "integer",
          "minimum":      1
        },
        "boost": {
          "description":  "Maximum boost speed of the ships (4 pips, straight-line)",
          "type":         "number",
          "minimum":      1
        },
        "cargoCapacity": {
          "type":         "integer",
          "minimum":      0
        },
        "class": {
          "description":  "Ship Class/Size [Small, Medium, Large]",
          "enum":         [1,2,3]
        },
        "dps": {
          "description":  "Cumulative DPS based on the in-game 1-10 statistic",
          "type":         "integer",
          "minimum":      0
        },
        "hullCost": {
          "description":  "Cost of the ship's hull",
          "type":         "integer",
          "minimum":      1
        },
        "hullMass": {
          "description":  "Mass of the Ship hull only",
          "type":         "number",
          "minimum":      1
        },
        "fuelCapacity": {
          "type":         "integer",
          "minimum":      1
        },
        "fullTankRange": {
          "description":  "Single Jump range with a full tank (unladenMass + fuel)",
          "type":         "number",
          "minimum":      0
        },
        "ladenMass": {
          "description":  "Mass of the Ship + fuel + cargo (hull + all components + fuel tank + cargo capacity)",
          "type":         "number",
          "minimum":      1
        },
        "ladenRange": {
          "description":  "Single Jump range with full cargo load, see ladenMass",
          "type":         "number",
          "minimum":      0
        },
        "masslock": {
          "description":  "Mass Lock Factor of the Ship",
          "type":         "integer",
          "minimum":      1
        },
        "shieldStrength": {
          "description":  "Shield strengh in Mega Joules (Mj)",
          "type":         "number",
          "minimum":      0
        },
        "speed": {
          "description":  "Maximum speed of the ships (4 pips, straight-line)",
          "type":         "number",
          "minimum":      1
        },
        "totalCost":  {
          "type":         "integer",
          "minimum":      1
        },
        "unladenRange": {
          "description":  "Single Jump range when unladen, see unladenMass",
          "type":         "number",
          "minimum":      0
        },
        "unladenMass": {
          "description":  "Mass of the Ship (hull + all components)",
          "type":         "number",
          "minimum":      1
        }
      }
    }
  },
  "definitions": {
    "standardRatings":  { "enum": ["A", "B", "C", "D", "E", "F", "G", "H"] },
    "allRatings":       { "enum": ["A", "B", "C", "D", "E", "F", "G", "H", "I" ] }
  }
}

=== cmmcleod/coriolis/__tests__/fixtures/asp-test-detailed-export-v4.json
{
  "$schema": "http://cdn.coriolis.io/schemas/ship-loadout/4.json#",
  "name": "Multi-purpose Asp Explorer",
  "ship": "Asp Explorer",
  "references": [
    {
      "name": "Coriolis.io",
      "url": "https://coriolis.edcd.io/outfit/asp?code=0pftiFflfddsnf5------020202033c044002v62f2i.AwRj4yvI.CwRgDBldHnJA.H4sIAAAAAAAAA2P858DAwPCXEUhwHPvx%2F78YG5AltB7I%2F8%2F0TwImJboDSPJ%2F%2B%2Ff%2Fv%2FKlX%2F%2F%2Fi3AwMTBIfARK%2FGf%2BJwVSxArStVAYqOjvz%2F%2F%2FJVo5GRhE2IBc4SKQSSz%2FDGEmCa398P8%2F%2F2%2BgTf%2F%2FAwDFxwtofAAAAA%3D%3D&bn=Multi-purpose%20Asp%20Explorer",
      "code": "0pftiFflfddsnf5------020202033c044002v62f2i.AwRj4yvI.CwRgDBldHnJA.H4sIAAAAAAAAA2P858DAwPCXEUhwHPvx/78YG5AltB7I/8/0TwImJboDSPJ/+/f/v/KlX///i3AwMTBIfARK/Gf+JwVSxArStVAYqOjvz///JVo5GRhE2IBc4SKQSSz/DGEmCa398P8//2+gTf//AwDFxwtofAAAAA==",
      "shipId": "asp"
    }
  ],
  "components": {
    "standard": {
      "bulkheads": "Lightweight Alloy",
      "cargoHatch": {
        "enabled": false,
        "priority": 5
      },
      "powerPlant": {
        "class": 5,
        "rating": "A",
        "enabled": true,
        "priority": 2,
        "modifications": {
          "eff": -1850,
          "pgen": 6,
          "mass": 431
        },
        "blueprint": {
          "id": 64,
          "name": "Low emissions",
          "grade": 1
        }
      },
      "thrusters": {
        "class": 5,
        "rating": "D",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "optmul": 440,
          "integrity": -266,
          "thermload": -1326,
          "optmass": 520,
          "power": 241
        },
        "blueprint": {
          "id": 24,
          "name": "Clean",
          "grade": 1
        }
      },
      "frameShiftDrive": {
        "class": 5,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "mass": 5025,
          "integrity": -1539,
          "power": 2437,
          "optmass": 4870,
          "maxfuel": 370
        },
        "blueprint": {
          "id": 26,
          "name": "Increased range",
          "grade": 5
        }
      },
      "lifeSupport": {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "mass": -3923,
          "integrity": -1797
        },
        "blueprint": {
          "id": 49,
          "name": "Lightweight",
          "grade": 1
        }
      },
      "powerDistributor": {
        "class": 3,
        "rating": "D",
        "enabled": true,
        "priority": 1
      },
      "sensors": {
        "class": 5,
        "rating": "D",
        "enabled": true,
        "priority": 1
      },
      "fuelTank": {
        "class": 5,
        "rating": "C",
        "enabled": true,
        "priority": 1
      }
    },
    "hardpoints": [
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "utility": [
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Heat Sink Launcher",
        "name": "Heat Sink Launcher"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Heat Sink Launcher",
        "name": "Heat Sink Launcher"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Heat Sink Launcher",
        "name": "Heat Sink Launcher"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Point Defence",
        "name": "Point Defence"
      }
    ],
    "internal": [
      {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Fuel Scoop"
      },
      {
        "class": 5,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cargo Rack"
      },
      {
        "class": 3,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Generator"
      },
      {
        "class": 3,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cargo Rack"
      },
      {
        "class": 2,
        "rating": "G",
        "enabled": true,
        "priority": 1,
        "group": "Planetary Vehicle Hangar"
      },
      {
        "class": 1,
        "rating": "C",
        "enabled": true,
        "priority": 2,
        "group": "Scanner",
        "name": "Advanced Discovery Scanner"
      },
      {
        "class": 1,
        "rating": "C",
        "enabled": true,
        "priority": 2,
        "group": "Scanner",
        "name": "Detailed Surface Scanner"
      }
    ]
  },
  "stats": {
    "class": 2,
    "hullCost": 6135660,
    "speed": 250,
    "boost": 340,
    "boostEnergy": 13,
    "agility": 6,
    "baseShieldStrength": 140,
    "baseArmour": 210,
    "hullMass": 280,
    "masslock": 11,
    "pipSpeed": 0.13,
    "moduleCostMultiplier": 1,
    "fuelCapacity": 32,
    "cargoCapacity": 40,
    "ladenMass": 435.26,
    "armour": 378,
    "shield": 113.43,
    "shieldCells": 0,
    "totalCost": 48402550,
    "unladenMass": 363.26,
    "totalDpe": 0,
    "totalExplDpe": 0,
    "totalKinDpe": 0,
    "totalThermDpe": 0,
    "totalDps": 0,
    "totalExplDps": 0,
    "totalKinDps": 0,
    "totalThermDps": 0,
    "totalSDps": 0,
    "totalExplSDps": 0,
    "totalKinSDps": 0,
    "totalThermSDps": 0,
    "totalEps": 1.2,
    "totalHps": 1,
    "shieldExplRes": 0.5,
    "shieldKinRes": 0.6,
    "shieldThermRes": 1.2,
    "hullExplRes": 1.4,
    "hullKinRes": 1.2,
    "hullThermRes": 1,
    "powerAvailable": 20.41,
    "powerRetracted": 11.91,
    "powerDeployed": 11.91,
    "unladenRange": 50.45,
    "fullTankRange": 47.03,
    "ladenRange": 42.71,
    "unladenFastestRange": 317.24,
    "ladenFastestRange": 287.02,
    "maxJumpCount": 7,
    "topSpeed": 274.01,
    "topBoost": 372.65
  }
}
