=== cmmcleod/coriolis/src/schemas/ship-loadout/4.json
{
  "$schema":            "http://json-schema.org/draft-04/schema#",
  "id":                 "https://coriolis.edcd.io/schemas/ship-loadout/4.json#",
  "title":              "Ship Loadout",
  "type":               "object",
  "description":        "The details for a specific ship build/loadout",
  "required":           ["name", "ship", "components"],
  "properties": {
    "name": {
      "description":    "The name of the build/loadout",
      "type":           "string",
      "minLength":      1
    },
    "ship": {
      "description":    "The full display name of the ship",
      "type":           "string",
      "minimum":        3
    },
    "manufacturer": {
      "description":    "The ship manufacturer",
      "type":           "string"
    },
    "references" : {
      "description":    "3rd Party references and/or links to this build/loadout",
      "type":           "array",
      "items": {
        "type":                 "object",
        "required":             ["name","url"],
        "additionalProperties": true,
        "properties": {
          "name": {
            "description":  "The name of the 3rd party, .e.g 'Coriolis.io' or 'E:D Shipyard'",
            "type":         "string"
          },
          "url": {
            "description":  "The link/url to the 3rd party referencing this build/loadout",
            "type":         "string"
          }
        }
      }
    },
    "components": {
      "description":                "The components used by this build",
      "type":                       "object",
      "additionalProperties":       false,
      "required":                   ["standard", "internal", "hardpoints", "utility"],
      "properties": {
        "standard": {
          "description":            "The set of standard components across all ships",
          "type":                   "object",
          "additionalProperties":   false,
          "required":               ["bulkheads", "powerPlant", "thrusters", "frameShiftDrive", "lifeSupport", "powerDistributor", "sensors", "fuelTank", "cargoHatch"],
          "properties": {
            "bulkheads": {
              "enum":               ["Lightweight Alloy", "Reinforced Alloy", "Military Grade Composite", "Mirrored Surface Composite", "Reactive Surface Composite"]
            },
            "cargoHatch": {
              "required": ["enabled", "priority"],
              "properties": {
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 }
              }
            },
            "powerPlant": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
                "blueprint": { "type": "object" },
                "modifications": { "type": "object" }
              }
            },
            "thrusters": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
                "name": {
                  "description": "The name identifing the thrusters (if applicable), e.g. 'Enhanced Performance'",
                  "type": "string"
                },
                "blueprint": { "type": "object" },
                "modifications": { "type": "object" }
              }
            },
            "frameShiftDrive": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 2, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
                "blueprint": { "type": "object" },
                "modifications": { "type": "object" }
              }
            },
            "lifeSupport": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 6 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
                "blueprint": { "type": "object" },
                "modifications": { "type": "object" }
              }
            },
            "powerDistributor": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
                "blueprint": { "type": "object" },
                "modifications": { "type": "object" }
              }
            },
            "sensors": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 8 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
                "blueprint": { "type": "object" },
                "modifications": { "type": "object" }
              }
            },
            "fuelTank": {
              "required": ["class", "rating", "enabled", "priority"],
              "properties": {
                "class": { "type": "integer", "minimum": 1, "maximum": 6 },
                "rating": { "$ref": "#/definitions/standardRatings" },
                "enabled": { "type": "boolean" },
                "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
                "blueprint": { "type": "object" },
                "modifications": { "type": "object" }
              }
            }
          }
        },
        "internal": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group"],
            "properties" : {
              "class": { "type": "integer", "minimum": 1, "maximum": 8 },
              "rating": { "$ref": "#/definitions/standardRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "group": {
                "description": "The group of the component, e.g. 'Shield Generator', or 'Cargo Rack'",
                "type": "string"
              },
              "name": {
                "description": "The name identifying the component (if applicable), e.g. 'Advance Discovery Scanner', or 'Detailed Surface Scanner'",
                "type": "string"
              },
              "blueprint": { "type": "object" },
              "modifications": { "type": "object" }
            }
          },
          "minItems": 3
        },
        "hardpoints": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group", "mount"],
            "properties" : {
              "class": { "type": "integer", "minimum": 1, "maximum": 4 },
              "rating": { "$ref": "#/definitions/allRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "mount": { "type": "string", "enum": ["Fixed", "Gimballed", "Turret"] },
              "group": {
                "description": "The group of the component, e.g. 'Beam Laser', or 'Missile Rack'",
                "type": "string"
              },
              "name": {
                "description": "The name identifing the component (if applicable), e.g. 'Retributor', or 'Mining Lance'",
                "type": "string"
              },
              "blueprint": { "type": "object" },
              "modifications": { "type": "object" }
            }
          },
          "minItems": 1
        },
        "utility": {
          "type": "array",
          "items": {
            "type": ["object", "null"],
            "required": ["class", "rating", "enabled", "priority", "group"],
            "properties" : {
              "class": { "type": "integer", "minimum": 0, "maximum": 0 },
              "rating": { "$ref": "#/definitions/allRatings" },
              "enabled": { "type": "boolean" },
              "priority": { "type": "integer", "minimum": 1, "maximum": 5 },
              "group": {
                "description": "The group of the component, e.g. 'Shield Booster', or 'Kill Warrant Scanner'",
                "type": "string"
              },
              "name": {
                "description": "The name identifing the component (if applicable), e.g. 'Point Defence', or 'Electronic Countermeasure'",
                "type": "string"
              },
              "blueprint": { "type": "object" },
              "modifications": { "type": "object" }
            }
          },
          "minItems": 1
        }
      }
    },
    "stats": {
      "description":          "Optional statistics from the build",
      "type":                 "object",
      "additionalProperties": true,
      "properties": {
        "agility": {
          "type":         "integer",
          "minimum":      0
        },
        "armour": {
          "description":  "Sum of base armour + any hull reinforcements",
          "type":         "number",
          "minimum":      1
        },
        "armourAdded":{
          "description":  "Armour added through Hull reinforcement",
          "type":         "number",
          "minimum":      0
        },
        "baseShieldStrength": {
          "type":         "number",
          "minimum":      1
        },
        "baseArmour":  {
          "type":         "integer",
          "minimum":      1
        },
        "boost": {
          "description":  "Maximum boost speed of the ships (4 pips, straight-line)",
          "type":         "number",
          "minimum":      0
        },
        "cargoCapacity": {
          "type":         "integer",
          "minimum":      0
        },
        "class": {
          "description":  "Ship Class/Size [Small, Medium, Large]",
          "enum":         [1,2,3]
        },
        "totalDps": {
          "description":  "Total damage dealt per second of all weapons",
          "type":         "number",
          "minimum":      0
        },
        "totalEps": {
          "description":  "Total energy consumed per second of all weapons",
          "type":         "number",
          "minimum":      0
        },
        "totalHps": {
          "description":  "Total heat generated per second of all weapons",
          "type":         "number",
          "minimum":      0
        },
        "hullCost": {
          "description":  "Cost of the ship's hull",
          "type":         "integer",
          "minimum":      1
        },
        "hullMass": {
          "description":  "Mass of the Ship hull only",
          "type":         "number",
          "minimum":      1
        },
        "hullExplRes": {
          "description":  "Multiplier for explosive damage to hull",
          "type":         "number"
        },
        "hullKinRes": {
          "description":  "Multiplier for kinetic damage to hull",
          "type":         "number"
        },
        "hullThermRes": {
          "description":  "Multiplier for thermal damage to hull",
          "type":         "number"
        },
        "fuelCapacity": {
          "type":         "integer",
          "minimum":      1
        },
        "fullTankRange": {
          "description":  "Single Jump range with a full tank (unladenMass + fuel)",
          "type":         "number",
          "minimum":      0
        },
        "ladenMass": {
          "description":  "Mass of the Ship + fuel + cargo (hull + all components + fuel tank + cargo capacity)",
          "type":         "number",
          "minimum":      1
        },
        "ladenRange": {
          "description":  "Single Jump range with full cargo load, see ladenMass",
          "type":         "number",
          "minimum":      0
        },
        "masslock": {
          "description":  "Mass Lock Factor of the Ship",
          "type":         "integer",
          "minimum":      1
        },
        "shield": {
          "description":  "Shield strength in Mega Joules (Mj)",
          "type":         "number",
          "minimum":      0
        },
        "shieldExplRes": {
          "description":  "Multiplier for explosive damage to shields",
          "type":         "number"
        },
        "shieldKinRes": {
          "description":  "Multiplier for kinetic damage to shields",
          "type":         "number"
        },
        "shieldThermRes": {
          "description":  "Multiplier for thermal damage to shields",
          "type":         "number"
        },
        "speed": {
          "description":  "Maximum speed of the ships (4 pips, straight-line)",
          "type":         "number",
          "minimum":      1
        },
        "totalCost":  {
          "description":  "Total cost of the loadout, including discounts",
          "type":         "number"
        },
        "unladenRange": {
          "description":  "Single Jump range when unladen, see unladenMass",
          "type":         "number",
          "minimum":      0
        },
        "unladenMass": {
          "description":  "Mass of the Ship (hull + all components)",
          "type":         "number",
          "minimum":      1
        }
      }
    }
  },
  "definitions": {
    "standardRatings":  { "enum": ["A", "B", "C", "D", "E", "F", "G", "H"] },
    "allRatings":       { "enum": ["A", "B", "C", "D", "E", "F", "G", "H", "I" ] }
  }
}

=== cmmcleod/coriolis/__tests__/fixtures/anaconda-test-detailed-export-v4.json
{
  "$schema": "http://cdn.coriolis.io/schemas/ship-loadout/4.json#",
  "name": "Test My Ship",
  "ship": "Anaconda",
  "references": [
    {
      "name": "Coriolis.io",
      "url": "http://localhost:3300/outfit/anaconda/48A6A6A5A8A8A5C2c0o0o0o1m1m0q0q0404-0l0b0100034k5n052d04--0303326b.AwRj4zNKqA==.CwBhCYzBGW9qCTSqs5xA.H4sIAAAAAAAAA2MUe8HMwPD-PwDDhxeuCAAAAA==?bn=Test%20My%20Ship",
      "old-code": "48A6A6A5A8A8A5C2c0o0o0o1m1m0q0q0404-0l0b0100034k5n052d04--0303326b.AwRj4zNKqA==.CwBhCYzBGW9qCTSqs5xA.H4sIAAAAAAAAA2MUe8HMwPD-PwDDhxeuCAAAAA==",
      "code": "4putkFklkdzsuf52c0o0o0o1m1m0q0q0404-0l0b0100034k5n052d04--0303326b.AwRj4zNKqA==.CwBhCYzBGW9qCTSqs5xA.H4sIAAAAAAAAA2MUe8HMwPD-PwDDhxeuCAAAAA==",
      "shipId": "anaconda"
    }
  ],
  "components": {
    "standard": {
      "bulkheads": "Reactive Surface Composite",
      "cargoHatch": {
        "enabled": false,
        "priority": 5
      },
      "powerPlant": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "modifications": {
          "pgen": 1000
	}
      },
      "thrusters": {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "frameShiftDrive": {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 3
      },
      "lifeSupport": {
        "class": 5,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "powerDistributor": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "sensors": {
        "class": 8,
        "rating": "A",
        "enabled": true,
        "priority": 1
      },
      "fuelTank": {
        "class": 5,
        "rating": "C",
        "enabled": true,
        "priority": 1
      }
    },
    "hardpoints": [
      {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 2,
        "group": "Plasma Accelerator",
        "mount": "Fixed"
      },
      {
        "class": 3,
        "rating": "D",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 3,
        "rating": "D",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 3,
        "rating": "D",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cannon",
        "mount": "Turret"
      },
      {
        "class": 2,
        "rating": "E",
        "enabled": true,
        "priority": 2,
        "group": "Cannon",
        "mount": "Turret"
      },
      {
        "class": 1,
        "rating": "F",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      },
      {
        "class": 1,
        "rating": "F",
        "enabled": true,
        "priority": 2,
        "group": "Beam Laser",
        "mount": "Turret"
      }
    ],
    "utility": [
      {
        "class": 0,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Booster"
      },
      {
        "class": 0,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Booster"
      },
      null,
      {
        "class": 0,
        "rating": "C",
        "enabled": true,
        "priority": 2,
        "group": "Kill Warrant Scanner"
      },
      {
        "class": 0,
        "rating": "C",
        "enabled": true,
        "priority": 2,
        "group": "Cargo Scanner"
      },
      {
        "class": 0,
        "rating": "F",
        "enabled": false,
        "priority": 1,
        "group": "Electronic Countermeasure",
        "name": "Electronic Countermeasure"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 1,
        "group": "Chaff Launcher",
        "name": "Chaff Launcher"
      },
      {
        "class": 0,
        "rating": "I",
        "enabled": true,
        "priority": 2,
        "group": "Point Defence",
        "name": "Point Defence"
      }
    ],
    "internal": [
      {
        "class": 7,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Generator"
      },
      {
        "class": 6,
        "rating": "A",
        "enabled": true,
        "priority": 1,
        "group": "Shield Cell Bank"
      },
      {
        "class": 6,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      {
        "class": 5,
        "rating": "D",
        "enabled": true,
        "priority": 1,
        "group": "Hull Reinforcement Package"
      },
      {
        "class": 5,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      null,
      null,
      null,
      {
        "class": 4,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      {
        "class": 4,
        "rating": "E",
        "enabled": true,
        "priority": 1,
        "group": "Cargo Rack"
      },
      {
        "class": 4,
        "rating": "A",
        "enabled": true,
        "priority": 3,
        "group": "Fuel Scoop"
      },
      {
        "class": 2,
        "rating": "A",
        "enabled": true,
        "priority": 3,
        "group": "Frame Shift Drive Interdictor"
      }
    ]
  },
  "stats": {
    "class": 3,
    "fighterHangars": 1,
    "hullCost": 141889930,
    "speed": 180,
    "topSpeed": 186.5,
    "boost": 240,
    "boostEnergy": 27,
    "topBoost": 249.34,
    "topPitch": 25.97,
    "topRoll": 62.34,
    "topYaw": 10.39,
    "topSpeed": 187.01,
    "totalCost": 882362058,
    "totalDpe": 142.68,
    "totalDps": 101.13,
    "totalEps": 22.71,
    "totalHps": 677.29,
    "totalExplDpe": 0,
    "totalExplDps": 0,
    "totalExplSDps": 0,
    "totalHps": 33.62,
    "totalKinDpe": 116.29,
    "totalKinDps": 16.01,
    "totalKinSDps": 12.09,
    "totalSDps": 89.99,
    "totalThermDpe": 20.44,
    "totalThermDps": 53.82,
    "totalThermSDps": 53.82,
    "baseShieldStrength": 350,
    "baseArmour": 945,
    "hullExplRes": 0.22,
    "hullKinRes": 0.27,
    "hullMass": 400,
    "hullThermRes": -0.36,
    "masslock": 23,
    "pipSpeed": 0.14,
    "pitch": 25,
    "moduleCostMultiplier": 1,
    "modulearmour": 0,
    "moduleprotection": 0,
    "fuelCapacity": 32,
    "cargoCapacity": 128,
    "ladenMass": 1323.2,
    "armour": 2227.5,
    "baseArmour": 525,
    "unladenMass": 1163.2,
    "powerAvailable": 39.6,
    "powerRetracted": 23.33,
    "powerDeployed": 34.13,
    "roll": 60,
    "unladenRange": 18.74,
    "yaw": 10,
    "fullTankRange": 18.36,
    "hardness": 65,
    "ladenRange": 16.59,
    "unladenFastestRange": 74.2,
    "ladenFastestRange": 66.96,
    "maxJumpCount": 4,
    "shield": 833,
    "shieldCells": 1840,
    "shieldExplRes": 0.5,
    "shieldKinRes": 0.4,
    "shieldThermRes": -0.2
  }
}
